openapi: 3.1.0
info:
  title: API Without Authentication
  description: Template for APIs that do not require authentication.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /data:
    get:
      operationId: getData
      summary: Retrieve data from the API
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
